### Analisando Dados Cidades Digitais

Dados obtidos do Portal Brasileiro de Dados Abertos: http://dados.gov.br/dataset/cidades-digitais

In [1]:
#Importando bibliotecas
import pandas as pd
import numpy as np

In [2]:
#Lendo o arquivo csv
df_cidades_digitais = pd.read_csv('cidades_digitais.csv', sep = ';', encoding = 'latin1')

In [3]:
#Visualizando as primeiras linhas do dataframe
df_cidades_digitais.head()

,UF,CIDADE,IBGE,POPULAÇÃO,VALOR_TOTAL_PREVISTO,STATUS,PONTOS_ATENDIDOS,VALOR_INVESTIDO
0,AC,Tarauacá,1200609,38819,"484.547,53",Sem Previsão,8,0
1,AL,Delmiro Gouveia,2702405,51997,"1.169.381,70",Sem Previsão,43,0
2,AL,Estrela de Alagoas,2702553,18306,"527.206,83",Sem Previsão,39,0
3,AM,Autazes,1300300,37033,"1.171.151,92",Sem Previsão,51,0
4,AM,Benjamin Constant,1300607,39484,"844.586,48",Sem Previsão,12,0

In [6]:
#Deletando a coluna IBGE
del df_cidades_digitais['IBGE']

In [7]:
#Visualizando se a coluna foi apagada
df_cidades_digitais.head()

,UF,CIDADE,POPULAÇÃO,VALOR_TOTAL_PREVISTO,STATUS,PONTOS_ATENDIDOS,VALOR_INVESTIDO
0,AC,Tarauacá,38819,"484.547,53",Sem Previsão,8,0
1,AL,Delmiro Gouveia,51997,"1.169.381,70",Sem Previsão,43,0
2,AL,Estrela de Alagoas,18306,"527.206,83",Sem Previsão,39,0
3,AM,Autazes,37033,"1.171.151,92",Sem Previsão,51,0
4,AM,Benjamin Constant,39484,"844.586,48",Sem Previsão,12,0

In [8]:
#Aplicando Group By para agrupar as cidades por UF
cidades_by_uf = df_cidades_digitais.groupby('UF')

In [9]:
type(cidades_by_uf)

pandas.core.groupby.generic.DataFrameGroupBy

In [10]:
#Visualizando os grupos
cidades_by_uf.groups

{'AC': Int64Index([0], dtype='int64'),
 'AL': Int64Index([1, 2], dtype='int64'),
 'AM': Int64Index([3, 4, 5, 6, 7, 8, 9, 10, 11], dtype='int64'),
 'AP': Int64Index([12, 13, 14, 15, 16, 17], dtype='int64'),
 'BA': Int64Index([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
             35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
            dtype='int64'),
 'CE': Int64Index([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
             68, 69, 70, 71, 72, 73, 74, 75, 76],
            dtype='int64'),
 'DF': Int64Index([77], dtype='int64'),
 'ES': Int64Index([78, 79, 80, 81], dtype='int64'),
 'GO': Int64Index([82, 83, 84, 85, 86, 87, 88, 89, 90, 91], dtype='int64'),
 'MA': Int64Index([ 92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
             105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117],
            dtype='int64'),
 'MG': Int64Index([118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
             131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
             144, 145],
            dtype='int64'),
 'MS': Int64Index([146, 147, 148], dtype='int64'),
 'MT': Int64Index([149, 150, 151, 152], dtype='int64'),
 'PA': Int64Index([153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
             166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176],
            dtype='int64'),
 'PB': Int64Index([177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
             190, 191, 192, 193, 194],
            dtype='int64'),
 'PE': Int64Index([195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
             208, 209, 210],
            dtype='int64'),
 'PI': Int64Index([211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223,
             224, 225, 226, 227, 228],
            dtype='int64'),
 'PR': Int64Index([229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
             242, 243, 244, 245],
            dtype='int64'),
 'RJ': Int64Index([246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258,
             259, 260],
            dtype='int64'),
 'RN': Int64Index([261, 262, 263, 264, 265, 266, 267, 268, 269], dtype='int64'),
 'RO': Int64Index([270, 271], dtype='int64'),
 'RR': Int64Index([272], dtype='int64'),
 'RS': Int64Index([273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
             286, 287, 288],
            dtype='int64'),
 'SC': Int64Index([289, 290, 291, 292, 293, 294], dtype='int64'),
 'SE': Int64Index([295, 296, 297, 298], dtype='int64'),
 'SP': Int64Index([299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
             312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
             325, 326, 327, 328, 329, 330, 331, 332, 333],
            dtype='int64'),
 'TO': Int64Index([334, 335, 336, 337], dtype='int64')}

In [11]:
#Visualizando o número de grupos criados
len(cidades_by_uf.groups)

27

In [22]:
#Visualizando o tamanho de cada grupo e armazenando na variável ordenar_uf
ordenar_uf = cidades_by_uf.size()
ordenar_uf

UF
AC     1
AL     2
AM     9
AP     6
BA    33
CE    26
DF     1
ES     4
GO    10
MA    26
MG    28
MS     3
MT     4
PA    24
PB    18
PE    16
PI    18
PR    17
RJ    15
RN     9
RO     2
RR     1
RS    16
SC     6
SE     4
SP    35
TO     4
dtype: int64

In [23]:
#Ordenando os grupos por ordem crescente
ordenar_uf.sort_values(ascending=False)

UF
SP    35
BA    33
MG    28
MA    26
CE    26
PA    24
PI    18
PB    18
PR    17
PE    16
RS    16
RJ    15
GO    10
RN     9
AM     9
AP     6
SC     6
ES     4
TO     4
MT     4
SE     4
MS     3
RO     2
AL     2
DF     1
RR     1
AC     1
dtype: int64

In [24]:
#Agrupando por UF e STATUS
cidades_by_uf_status = df_cidades_digitais.groupby(['UF', 'STATUS'])

In [25]:
#Total agrupado
cidades_by_uf_status.size()

UF  STATUS
AC  Sem Previsão     1
AL  Sem Previsão     2
AM  Concluída        3
    Sem Previsão     6
AP  Concluída        1
    Sem Previsão     5
BA  Concluída        9
    Sem Previsão    24
CE  Concluída       11
    Sem Previsão    15
DF  Concluída        1
ES  Sem Previsão     4
GO  Sem Previsão    10
MA  Concluída        1
    Sem Previsão    25
MG  Concluída        2
    Em andamento     1
    Sem Previsão    25
MS  Sem Previsão     3
MT  Sem Previsão     4
PA  Concluída        9
    Sem Previsão    15
PB  Concluída        6
    Em andamento     3
    Sem Previsão     9
PE  Concluída        1
    Sem Previsão    15
PI  Concluída        3
    Sem Previsão    15
PR  Concluída        7
    Em andamento     1
    Sem Previsão     9
RJ  Concluída        1
    Em andamento     2
    Sem Previsão    12
RN  Concluída        1
    Sem Previsão     8
RO  Sem Previsão     2
RR  Sem Previsão     1
RS  Concluída        4
    Em andamento     2
    Sem Previsão    10
SC  Concluída        1
    Sem Previsão     5
SE  Sem Previsão     4
SP  Concluída        8
    Em andamento     2
    Sem Previsão    25
TO  Sem Previsão     4
dtype: int64

In [26]:
df_cidades_digitais.head()

,UF,CIDADE,POPULAÇÃO,VALOR_TOTAL_PREVISTO,STATUS,PONTOS_ATENDIDOS,VALOR_INVESTIDO
0,AC,Tarauacá,38819,"484.547,53",Sem Previsão,8,0
1,AL,Delmiro Gouveia,51997,"1.169.381,70",Sem Previsão,43,0
2,AL,Estrela de Alagoas,18306,"527.206,83",Sem Previsão,39,0
3,AM,Autazes,37033,"1.171.151,92",Sem Previsão,51,0
4,AM,Benjamin Constant,39484,"844.586,48",Sem Previsão,12,0

In [27]:
cidades_uf3 = df_cidades_digitais.set_index('STATUS')

In [28]:
cidades_uf3

,UF,CIDADE,POPULAÇÃO,VALOR_TOTAL_PREVISTO,PONTOS_ATENDIDOS,VALOR_INVESTIDO
STATUS,,,,,,
Sem Previsão,AC,Tarauacá,38819,"484.547,53",8,0
Sem Previsão,AL,Delmiro Gouveia,51997,"1.169.381,70",43,0
Sem Previsão,AL,Estrela de Alagoas,18306,"527.206,83",39,0
Sem Previsão,AM,Autazes,37033,"1.171.151,92",51,0
Sem Previsão,AM,Benjamin Constant,39484,"844.586,48",12,0
...,...,...,...,...,...,...
Sem Previsão,SP,Vargem Grande do Sul,41807,"1.525.640,54",47,0
Sem Previsão,TO,Paraíso do Tocantins,49076,"1.872.693,90",49,0
Sem Previsão,TO,Ponte Alta do Bom Jesus,4649,"251.266,44",9,"23.969,90"
Sem Previsão,TO,Porto Nacional,52182,"1.101.168,76",61,0
Sem Previsão,TO,São Miguel do Tocantins,11597,"592.549,70",20,0

In [41]:
#Aplicando group by
cidades_uf3.groupby(['UF', 'VALOR_INVESTIDO']).head()

,UF,CIDADE,POPULAÇÃO,VALOR_TOTAL_PREVISTO,PONTOS_ATENDIDOS,VALOR_INVESTIDO
STATUS,,,,,,
Sem Previsão,AC,Tarauacá,38819,"484.547,53",8,0
Sem Previsão,AL,Delmiro Gouveia,51997,"1.169.381,70",43,0
Sem Previsão,AL,Estrela de Alagoas,18306,"527.206,83",39,0
Sem Previsão,AM,Autazes,37033,"1.171.151,92",51,0
Sem Previsão,AM,Benjamin Constant,39484,"844.586,48",12,0
...,...,...,...,...,...,...
Concluída,SP,Socorro,39565,"740.416,36",24,"711.125,40"
Sem Previsão,TO,Paraíso do Tocantins,49076,"1.872.693,90",49,0
Sem Previsão,TO,Ponte Alta do Bom Jesus,4649,"251.266,44",9,"23.969,90"
Sem Previsão,TO,Porto Nacional,52182,"1.101.168,76",61,0
Sem Previsão,TO,São Miguel do Tocantins,11597,"592.549,70",20,0